#ifndef __WEIKU_CONFIG_H__
#define __WEIKU_CONFIG_H__

// Generated by the WEIKU source folder's sync_assets.ps1.
// Edit timing.ini beside that script, then run the script again.
namespace WeikuConfig
{
    static const float kIdleSeconds = 1.0f;
    static const float kShootSeconds = 1.5f;
    static const float kFlySeconds = 0.8f;
    static const int kIdleFrameCount = 18;
    static const int kShootFrameCount = 26;
    static const int kFlyFrameCount = 10;
    static const int kFireFrameIndex = 25;
    static const int kShootTicks = (int)(kShootSeconds * 100.0f + 0.5f);
    static const int kFireTick = (kFireFrameIndex * kShootTicks + kShootFrameCount - 1) / kShootFrameCount;
    static const int kFireCounter = kShootTicks + 1 - (kFireTick > 0 ? kFireTick : 1);
}

#endif
